version: "3"

services:
 
      api-docker:
            image: api-docker-dapper:latest
            container_name: api-docker-dapper
            build:
                  context: ../ApiDemo-Docker-Com-Dapper
                  dockerfile: Dockerfile
            ports: 
                 - "49155:49155"
            environment:
                 - ASPNETCORE_ENVIRONMENT=Development
                 - ASPNETCORE_URLS=http://*:49155
            
            depends_on:
                - sql-server

      sql-server:
            image: mcr.microsoft.com/mssql/server:2019-latest
            container_name: apidocker-sql-server
            environment:
                - SA_PASSWORD=Numsey#2022
                - ACCEPT_EULA=Y           
            ports: 
                - "1444:1433"
            